kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpinntektsmelding
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /fpinntektsmelding/internal/health/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fpinntektsmelding/internal/health/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /fpinntektsmelding/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpinntektsmelding/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - type: {{db.dbVersion}}
        databases:
          - name: fpinntektsmelding
            envVarPrefix: DB
        tier: {{db.dbTier}}
        diskAutoresize: {{db.dbDiskAutoresize}}
        highAvailability: {{db.dbHighAvailability}}
        pointInTimeRecovery: {{db.dbPointInTimeRecovery}}
        collation: nb_NO.UTF8
        retainedBackups: {{db.dbRetainedBackups}}
        autoBackupHour: 2
        maintenance:
          day: 1
          hour: 4
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          {{#each groups as |group|}}
          - id: "{{group.uuid}}"
          {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: fpinntektsmelding-frontend
        - application: fp-swagger
          permissions:
            scopes:
              - swagger
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: {{environment}}-fss
      {{#if devOnly}}
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
      {{/if}}
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: fpdokgen
      external:
        - host: pdl-api.{{environment}}-fss-pub.nais.io
        - host: team-inntekt-proxy.{{environment}}-fss-pub.nais.io
        - host: fpsak-api.{{environment}}-fss-pub.nais.io
        - host: ereg-services.{{environment}}-fss-pub.nais.io
        - host: aareg-services.{{environment}}-fss-pub.nais.io
      {{#if devOnly}}
        - host: dokarkiv-q2.{{environment}}-fss-pub.nais.io
        - host: platform.tt02.altinn.no
      {{else}}
        - host: dokarkiv.{{environment}}-fss-pub.nais.io
        - host: platform.altinn.no
      {{/if}}
