ALTER TABLE INNTEKTSMELDING
    ADD UUID UUID;

COMMENT ON COLUMN INNTEKTSMELDING.UUID IS 'En unik uuid som identifiserer inntektsmeldingen';
create unique index UIDX_INNTEKTSMELDING_UUID on INNTEKTSMELDING (UUID);
