create index IDX_FORESPOERSEL_BRUKER_AKTOER_ID on FORESPOERSEL (BRUKER_AKTOER_ID);
create index IDX_FORESPOERSEL_FAGSYSTEM_SAKSNUMMER on FORESPOERSEL (FAGSYSTEM_SAKSNUMMER);
create unique index UIDX_FORESPOERSEL_SAK_ID on FORESPOERSEL (SAK_ID);
